### PR TITLE
viewer, various keyboard control fixes

### LINKED ISSUE #694: keyboard shortcuts don't work when popup is active
Either it should be clear that it needs to be closed to start using them, or they should work when it's open.

### PR DESCRIPTION
**Pull request by jrochkind**
closes #694 and #791

### CODE REVIEW

**Comment by jrochkind** [comment]
I thought I was done before, but now I think I'm done again! Tested on IE11.

File: app/assets/javascripts/chf_image_viewer.js [hunk 1]
```diff
@@ -234,123 +243,116 @@ ChfImageViewer.prototype.locationWithNewPath = function(newPath) {
 };
 
 ChfImageViewer.prototype.onKeyDown = function(event) {
-  if (this.dropdownVisible) {
```
Comment (hackmastera) [inline app/assets/javascripts/chf_image_viewer.js]: It seems like you're removing all references to this? Maybe you can delete these, also https://github.com/chemheritage/chf-sufia/blob/7eeb32669b4395042fdb7c50c1d148fde2642c63/app/assets/javascripts/chf_image_viewer.js#L479-L487

Comment (jrochkind) [reply app/assets/javascripts/chf_image_viewer.js]: yeah, I probably could, cause you're right, I did, good catch. But I sorta feel like leaving it there in case I need it later, this stuff has been kind of tricky to get right!

Comment (hackmastera) [reply app/assets/javascripts/chf_image_viewer.js]: 👍  works for me; I'll merge.

Comment (hackmastera) [reply app/assets/javascripts/chf_image_viewer.js]: haha i was too late
